GEOPY-0.1.0
MiraGeoscience/octree-creation-app pull request #8
Opened 2023-12-15 16:39 UTC by jamiefb

2023-12-15 18:07 UTC, andrewg-mira submitted a review, later dismissed

2023-12-15 21:26 UTC, sebhmg commented
@andrewg-mira , can you look at the configuration of badges before publishing?
![image](https://github.com/MiraGeoscience/octree-creation-app/assets/24550538/ad945482-f6e5-4893-bc6f-af7d30d557bc)

Also `geoapps-utils` in `pyproject.toml` would need to reference the version on PyPI, before that one can go on PyPI

2023-12-15 21:27 UTC, sebhmg requested changes
to release and publish on PyPI, need to refence the version of geoapps-utils on PyPI

Also:
- address TODO in readme for license
- add THIRD_PARTY_SOFTWARE.rst

2023-12-21 15:58 UTC, domfournier commented
Docs to be addressed on GEOPY-1270

2023-12-21 22:01 UTC, sebhmg commented on .codespellignore
> -astroid
not necessary anymore: tuned pre-commit to ignore text the lock files

2023-12-21 22:02 UTC, sebhmg commented on README.rst
> -|coverage| |maintainability| |precommit_ci| |docs| |style| |version| |status| |pyversions|
removing doc for now

2023-12-21 22:08 UTC, sebhmg commented on pylintrc
> +                  geoapps_utils
for some reason necessary for pylint to recognize these as third parties
and stop complaining about the import order

2023-12-21 22:09 UTC, sebhmg commented on pyproject.toml
> +Pillow = "^10.0.1"  # from geoh5py
if not forcing the version, they sometimes diverge, ending up with one installed by conda and another one with pip through geoph5py

2023-12-21 22:10 UTC, sebhmg commented on pyproject.toml
> +Pygments = "*"
to render rst code block in PyCharm

2023-12-21 22:10 UTC, sebhmg commented on pyproject.toml
> +known_third_party = ["geoh5py", "geoapps_utils"]
probably not necessary: pylint had an issue but not isort. I will revert that line

2023-12-21 22:12 UTC, sebhmg commented on tests/assets_path_test.py
> +    assert assets_path().is_dir()
from the application, we need an easy way to get the assets folder.
Writing is `assets_path(octree_creation_app.ASSETS_DIR)` everytime is somewhat heavy

2023-12-21 22:12 UTC, sebhmg commented on tests/assets_path_test.py
> -    assert assets_path(octree_creation_app.ASSETS_DIR).is_dir()
from the application, we need an easy way to get the assets folder.
Writing is `assets_path(octree_creation_app.ASSETS_DIR)` everytime is somewhat heavy

2023-12-21 22:13 UTC, sebhmg commented on octree_creation_app/__init__.py
> -ASSETS_DIR = __file__
ASSET_DIR is pointing to a file path: somewhat confusing
I am replacing by a function that uses the base implementation

2023-12-21 22:38 UTC, domfournier approved these changes

2023-12-21 22:50 UTC, sebhmg approved these changes

2023-12-21 22:56 UTC, merged